# -*- coding: utf-8 -*-
"""churn-model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xkR1GiommSS27HMXEZcl6q7fHXiVV3cX
"""

import pandas as pd
from sklearn.ensemble import RandomForestClassifier
import pickle

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
df_churn = pd.read_csv('telco-churn.csv')
print(df_churn.head())

print(df_churn.columns)

cols_to_keep = ['gender', 'tenure', 'MonthlyCharges', 'PaymentMethod', 'Churn']
df_churn = df_churn[cols_to_keep].copy()
df_churn.head()

df_churn.isna().sum()
df = df_churn.copy()

#create a dummy variables for gender and payment method
#https://builtin.com/machine-learning/streamlit-tutorial
encode = ['gender', 'PaymentMethod']
for col in encode:
    dummies = pd.get_dummies(df_churn[col], prefix=col)
    df = pd.concat([df, dummies], axis=1)
    del df[col]
print("----")
print(df.columns)

#map the values to 1 and 0
df['Churn'] = df['Churn'].map({'Yes': 1, 'No': 0})
X = df.drop('Churn', axis=1)
y = df['Churn']

clf = RandomForestClassifier()
clf.fit(X, y)

pickle.dump(clf, open('churn_clf.pkl', 'wb'))
